import { FormEvent, useEffect, useState } from "react";
import { ArrowRight, CheckCircle2, Network, Route, ShieldCheck, Sparkles, UserPlus } from "lucide-react";
import { trpc } from "../lib/trpc";

export default function Login() {
  const authQuery = trpc.auth.me.useQuery(undefined, { retry: false, refetchOnWindowFocus: false });
  const loginMutation = trpc.auth.login.useMutation({ onSuccess: () => { window.location.replace("/"); } });
  const [email, setEmail] = useState(""); const [password, setPassword] = useState(""); const [error, setError] = useState("");
  useEffect(() => { if (authQuery.data) window.location.replace("/"); }, [authQuery.data]);
  const submit = (event: FormEvent) => { event.preventDefault(); setError(""); loginMutation.mutate({ email, password }, { onError: () => setError("Email ou senha inválidos.") }); };
  return <main className="login-shell"><section className="login-visual"><div className="login-brand"><span className="login-brand-mark"><Network size={19} /></span><div><strong>NETPATH</strong><span>career ops / 01</span></div></div><div className="login-visual-content"><span className="eyebrow login-eyebrow"><span className="signal-pulse" /> PLATAFORMA DE CARREIRA EM REDES</span><h1>Transforme experiência em <em>próximo nível.</em></h1><p>Uma rota clara para estudar, praticar, validar certificações e construir evidências técnicas até a senioridade.</p><div className="login-proof-list"><span><CheckCircle2 size={15} /> Trilha com dependências reais</span><span><CheckCircle2 size={15} /> Cursos e eventos no mesmo lugar</span><span><CheckCircle2 size={15} /> Progresso salvo no seu perfil</span></div></div><div className="login-visual-footer"><span>NIC.br / Cisco / Juniper / Huawei</span><span>NETPATH 2026</span></div></section><section className="login-panel"><div className="login-panel-inner"><div className="login-mobile-brand"><span className="login-brand-mark"><Network size={18} /></span><strong>NETPATH</strong></div><div className="login-panel-heading"><span className="login-kicker"><Sparkles size={14} /> SUA JORNADA</span><h2>Entre para continuar.</h2><p>Use sua conta local do NetPath para salvar o nivelamento, acompanhar a trilha e receber recomendações.</p></div><div className="auth-mode-switch"><a className="active" href="/login" aria-current="page">Entrar</a><a href="/register"><UserPlus size={14} /> Criar conta</a></div><form className="local-auth-form" onSubmit={submit}><label>Email<input required type="email" value={email} onChange={event => setEmail(event.target.value)} autoComplete="email" /></label><label>Senha<input required type="password" value={password} onChange={event => setPassword(event.target.value)} autoComplete="current-password" /></label>{error && <p className="local-auth-error" role="alert">{error}</p>}<button className="login-primary" type="submit" disabled={loginMutation.isPending}>{loginMutation.isPending ? "Entrando..." : <>Entrar na minha conta <ArrowRight size={17} /></>}</button></form><div className="login-divider"><span>acesso local seguro</span></div><div className="login-security"><ShieldCheck size={18} /><div><strong>Autenticação própria do NetPath</strong><span>O NetPath não redireciona você para outra plataforma e nunca armazena sua senha em texto puro.</span></div></div><div className="login-return"><Route size={15} /><span>Primeira vez aqui? Crie sua conta e comece o nivelamento.</span></div><a className="login-back" href="/">Voltar para a página inicial</a></div></section></main>;
}
