import { useEffect, useMemo, useState, type ChangeEvent } from "react";
import { ArrowLeft, Check, FileLock2, FileText, LoaderCircle, LockKeyhole, ShieldCheck, Sparkles, Upload, UserRound } from "lucide-react";
import { trpc } from "../lib/trpc";

type ProfileData = { fullName: string; headline: string; location: string; linkedinUrl: string; portfolioUrl: string; summary: string; skills: string[]; certifications: string[]; experiences: Array<{ company: string; title: string; period: string; description: string }>; education: Array<{ institution: string; course: string; period: string }> };
const emptyProfile: ProfileData = { fullName: "", headline: "", location: "", linkedinUrl: "", portfolioUrl: "", summary: "", skills: [], certifications: [], experiences: [], education: [] };

export default function Profile() {
  const authQuery = trpc.auth.me.useQuery(undefined, { retry: false });
  const resumeQuery = trpc.profile.resume.useQuery(undefined, { enabled: Boolean(authQuery.data), retry: false });
  const [profile, setProfile] = useState<ProfileData>(emptyProfile);
  const [resumeId, setResumeId] = useState<number | null>(null);
  const [fileName, setFileName] = useState("");
  const [imported, setImported] = useState(false);
  const [consent, setConsent] = useState(false);
  const importMutation = trpc.profile.importResume.useMutation({ onSuccess: async (data) => { setResumeId(data.id); setProfile(data.profile); setFileName(data.fileName); setImported(true); await resumeQuery.refetch(); } });
  const confirmMutation = trpc.profile.confirmResume.useMutation({ onSuccess: () => resumeQuery.refetch() });
  const removeMutation = trpc.profile.removeResume.useMutation({ onSuccess: () => { setResumeId(null); setProfile(emptyProfile); setFileName(""); setImported(false); setConsent(false); resumeQuery.refetch(); } });

  useEffect(() => { if (resumeQuery.data) { setResumeId(resumeQuery.data.id); setFileName(resumeQuery.data.fileName); setProfile(resumeQuery.data.profile); setImported(resumeQuery.data.status === "draft"); } }, [resumeQuery.data]);
  const skillsText = useMemo(() => profile.skills.join(", "), [profile.skills]);
  const update = (field: keyof ProfileData, value: string) => setProfile((current) => ({ ...current, [field]: value }));
  const onFile = (event: ChangeEvent<HTMLInputElement>) => { const file = event.target.files?.[0]; if (!file || file.type !== "application/pdf") return; const reader = new FileReader(); reader.onload = () => { const base64 = String(reader.result).split(",")[1] ?? ""; importMutation.mutate({ fileName: file.name, mimeType: file.type, base64, consent }); }; reader.readAsDataURL(file); };
  const save = () => { if (resumeId) confirmMutation.mutate({ id: resumeId, profile }); };
  const remove = () => { if (resumeId && window.confirm("Remover este currículo e os dados extraídos?")) removeMutation.mutate({ id: resumeId }); };

  if (!authQuery.data) return <main className="profile-page"><div className="profile-guest"><LockKeyhole size={28} /><h1>Seu perfil profissional é privado.</h1><p>Entre no NetPath para anexar seu currículo e construir sua análise de carreira.</p><a className="primary-button" href="/login">Ir para o login</a></div></main>;

  return <main className="profile-page">
    <header className="profile-topbar"><a href="/" className="profile-back"><ArrowLeft size={15} /> Voltar para a trilha</a><span className="profile-private-label"><ShieldCheck size={14} /> área privada</span></header>
    <div className="profile-heading"><div><span className="eyebrow"><UserRound size={13} /> PERFIL PROFISSIONAL / 01</span><h1>Seu currículo, convertido em direção.</h1><p>Anexe o PDF exportado do LinkedIn, revise os dados extraídos e confirme o que deve alimentar sua rota NetPath.</p></div><div className="profile-lock-card"><FileLock2 size={19} /><strong>Somente você</strong><span>Dados protegidos e vinculados à sua conta.</span></div></div>
    <section className="profile-import-card"><div className="profile-import-icon"><Upload size={21} /></div><div className="profile-import-copy"><span className="mini-eyebrow">IMPORTAÇÃO MANUAL</span><h2>{resumeQuery.data ? "Currículo importado" : "Comece pelo seu currículo do LinkedIn"}</h2><p>{resumeQuery.data ? `${fileName} · ${(resumeQuery.data.sizeBytes / 1024 / 1024).toFixed(2)} MB · status: ${resumeQuery.data.status === "confirmed" ? "confirmado" : "em revisão"}` : "Aceitamos PDF de até 8 MB. O arquivo original fica em storage privado; o perfil extraído é cifrado no servidor."}</p></div><label className="profile-upload-button">{importMutation.isPending ? <><LoaderCircle className="spin" size={15} /> Lendo PDF...</> : <><Upload size={15} /> {resumeQuery.data ? "Trocar PDF" : "Anexar PDF"}</>}<input type="file" accept="application/pdf" onChange={onFile} disabled={importMutation.isPending || !consent} /></label></section>
    <label className="profile-consent"><input type="checkbox" checked={consent} onChange={(event) => setConsent(event.target.checked)} /><span>Autorizo o NetPath a processar este currículo para gerar minha prévia profissional. Posso remover os dados depois.</span></label>
    {(imported || resumeQuery.data) && <section className="profile-review"><div className="profile-review-heading"><div><span className="eyebrow"><Sparkles size={13} /> REVISÃO ANTES DE SALVAR</span><h2>Confirme sua leitura profissional.</h2><p>A extração é uma sugestão. Edite os campos e só confirme quando estiver correto.</p></div><span className="review-status"><FileText size={14} /> {resumeQuery.data?.status === "confirmed" ? "Perfil confirmado" : "Rascunho privado"}</span></div>
      <div className="profile-form-grid"><label>Nome completo<input value={profile.fullName} onChange={(event) => update("fullName", event.target.value)} /></label><label>Headline / cargo<input value={profile.headline} onChange={(event) => update("headline", event.target.value)} /></label><label>Localização<input value={profile.location} onChange={(event) => update("location", event.target.value)} /></label><label>LinkedIn<input value={profile.linkedinUrl} onChange={(event) => update("linkedinUrl", event.target.value)} /></label><label className="profile-wide">Resumo profissional<textarea value={profile.summary} onChange={(event) => update("summary", event.target.value)} rows={5} /></label><label className="profile-wide">Competências <small>separe por vírgulas</small><input value={skillsText} onChange={(event) => setProfile((current) => ({ ...current, skills: event.target.value.split(",").map((skill) => skill.trim()).filter(Boolean) }))} /></label></div>
      <div className="profile-evidence-grid"><div><span className="mini-eyebrow">EXPERIÊNCIAS IDENTIFICADAS</span>{profile.experiences.length ? profile.experiences.map((item, index) => <article className="profile-evidence" key={`${item.company}-${index}`}><strong>{item.title || "Experiência para revisar"}</strong><span>{item.company} {item.period && `· ${item.period}`}</span><p>{item.description}</p></article>) : <p className="profile-muted">Nenhuma experiência identificada.</p>}</div><div><span className="mini-eyebrow">FORMAÇÃO E CERTIFICAÇÕES</span>{profile.education.map((item, index) => <article className="profile-evidence" key={`${item.institution}-${index}`}><strong>{item.course}</strong><span>{item.institution} {item.period && `· ${item.period}`}</span></article>)}{profile.certifications.length > 0 && <div className="profile-tags">{profile.certifications.map((item) => <span key={item}>{item}</span>)}</div>}</div></div>
      <div className="profile-actions"><span><Check size={14} /> O PDF original não é exposto no perfil público.</span><div className="profile-action-buttons"><button className="profile-remove-button" onClick={remove} disabled={removeMutation.isPending}>Remover currículo</button><button className="primary-button" onClick={save} disabled={!resumeId || confirmMutation.isPending}>{confirmMutation.isPending ? "Salvando..." : "Confirmar meu perfil"} <Check size={15} /></button></div></div>{(confirmMutation.error || importMutation.error) && <p className="profile-error">Não foi possível processar o currículo. Verifique o PDF e tente novamente.</p>}</section>}
  </main>;
}
